name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 16
      - name: Build with Maven
        run: mvn --no-transfer-progress -Dmaven.test.skip=true --file pom.xml package

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 16
      - name: Test with Maven(JaCoCo)
        run: mvn --no-transfer-progress clean test jacoco:report
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
